const actionTypes = Object.freeze({
  CREATE_TODO_LIST: "CREATE_TODO_LIST",

  REMOVE_iTEM_TODO_LIST: "REMOVE_iTEM_TODO_LIST",
  REMOVE_ALL_TODO_LIST: "REMOVE_ALL_TODO_LIST",

  TODO_COMPLETED: "TODO_COMPLETED",

  TODO_EDIT: "TODO_EDIT",
});

export default actionTypes;
